=== AlvarooCM/1-DAW/LinguaxesDeMarcas/UD4/Exercise 25/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="photo" />
                            <xs:element name="tags" type="xs:string" />
                            <xs:element name="diameter" type="xs:positiveInteger" />
                            <xs:element name="weight" type="xs:positiveInteger" />
                            <xs:element name="price_fields" type="priceType" />
                            <xs:element name="size_fields" type="sizeType" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"></xs:minExclusive>
            <xs:fractionDigits value="2"></xs:fractionDigits>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Big"></xs:enumeration>
            <xs:enumeration value="Small"></xs:enumeration>
            <xs:enumeration value=" "></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AlvarooCM/1-DAW/LinguaxesDeMarcas/UD4/Exercise 25/items.xml
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="items.xsd">
    <item>
        <name>Manuel Rial Carnota</name>
        <photo></photo>
        <tags>PRET</tags>
        <diameter>40</diameter>
        <weight>12</weight>
        <price_fields>9999999999.99</price_fields>
        <size_fields>Big</size_fields>
    </item>
</items>
